APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:7JXA7aWwg4ZHzUEUcBvEus9kYfR8YsHTjbAmEo/4F5E=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sftpuser_property
DB_USERNAME=root
DB_PASSWORD=123456

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"


PAYPAL_CLIENT_ID= ASkKmYLVaJ-SV_HJAJbFJ5paGnjmgY9O8H3bGaUlV7P_t5kFPodqykiiancohNfTBRm-jeX-eJpLxNuC
PAYPAL_SECRET= ECDkr6rq0xUpIqJ0aMXtQ_1lEttHKbA-C8QRusWs28yeAEaJ355ENaN2mUu2FGQffMubzFrWDmd6lQ6H
PAYPAL_MODE=sandbox